version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
